spring:
  main:
    lazy-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=my-ddd
    username: postgres
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379