spring:
  main:
    lazy-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=my-ddd
    username: postgres
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
cache:
  caffeine:
    maximumSize: 1000
    expireAfterWriteSeconds: 300
  redis:
    timeToLiveSeconds: 600